/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author cahr913
 */
public class frmPantallaInicial extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPantallaInicial.class.getName());

    /**
     * Creates new form frmPantallaInicial
     */
    public frmPantallaInicial() {
        initComponents();
        
        //musiquita de fondo :)
        try {
            java.io.InputStream in = getClass().getResourceAsStream("/archive/intro.ogg");
            javax.sound.sampled.AudioInputStream audioEntrada = javax.sound.sampled.AudioSystem.getAudioInputStream(new java.io.BufferedInputStream(in));
            pnlSubmenus.setVisible(false);
    
            // Formato original (Vorbis) -> convertir a PCM
            javax.sound.sampled.AudioFormat formatoBase = audioEntrada.getFormat();
            javax.sound.sampled.AudioFormat formatoPCM = new javax.sound.sampled.AudioFormat(
                javax.sound.sampled.AudioFormat.Encoding.PCM_SIGNED,
                formatoBase.getSampleRate(),
                16,
                formatoBase.getChannels(),
                formatoBase.getChannels() * 2,
                formatoBase.getSampleRate(),
                false
            );
    
            javax.sound.sampled.AudioInputStream audioPCM = javax.sound.sampled.AudioSystem.getAudioInputStream(formatoPCM, audioEntrada);
    
            javax.sound.sampled.Clip clip = javax.sound.sampled.AudioSystem.getClip();
            clip.open(audioPCM);
            clip.loop(javax.sound.sampled.Clip.LOOP_CONTINUOUSLY);
        } catch (Exception e) {
            e.printStackTrace();
}
        // imagen abajo opciones
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/archive/VOICESINMYHEADVOICESINMYHEADVOICESINMYHEADVOICESINMYHEADVOICESINMYHEAD.jpg"));
        Image img1 = icono1.getImage().getScaledInstance(
                lblImagenGato.getWidth(), 
                lblImagenGato.getHeight(), 
                Image.SCALE_SMOOTH); // pon el ancho/alto que quieras
        lblImagenGato.setIcon(new ImageIcon(img1));
        
        // imagen MyWork.png
        ImageIcon Mywork = new ImageIcon(getClass().getResource("/archive/mywork.png"));
        Image img2 = Mywork.getImage().getScaledInstance(
                lblImagenMywork.getWidth(), 
                lblImagenMywork.getHeight(), 
                Image.SCALE_SMOOTH); // pon el ancho/alto que quieras
        lblImagenMywork.setIcon(new ImageIcon(img2));
        
        
        
        

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAbsolutoPrograma = new UI.PanelBackground("/archive/catacomb.png");
        pnlCalcStudio = new UI.PanelBackground("/archive/Stone6.png");
        lblNombreApp = new javax.swing.JLabel();
        lblImagenMywork = new javax.swing.JLabel();
        javax.swing.JPanel pnlOpciones = new UI.PanelBackground("/archive/fondoMenu.png");
        btnRectangulo = new UI.BotonBackground("/archive/fondoBotones.png");
        btnCuadrado = new UI.BotonBackground("/archive/fondoBotones.png");
        btnTriangulo = new UI.BotonBackground("/archive/fondoBotones.png");
        btnTrapecio = new UI.BotonBackground("/archive/fondoBotones.png");
        lblImagenGato = new javax.swing.JLabel();
        pnlSubmenus = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAbsolutoPrograma.setBackground(new java.awt.Color(222, 235, 166));
        pnlAbsolutoPrograma.setForeground(new java.awt.Color(153, 153, 153));

        pnlCalcStudio.setBackground(new java.awt.Color(95, 166, 213));
        pnlCalcStudio.setBorder(new javax.swing.border.MatteBorder(null));

        lblNombreApp.setBackground(new java.awt.Color(0, 0, 0));
        lblNombreApp.setFont(new java.awt.Font("Noto Sans Black", 3, 36)); // NOI18N
        lblNombreApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreApp.setText("CalcStudio");

        javax.swing.GroupLayout pnlCalcStudioLayout = new javax.swing.GroupLayout(pnlCalcStudio);
        pnlCalcStudio.setLayout(pnlCalcStudioLayout);
        pnlCalcStudioLayout.setHorizontalGroup(
            pnlCalcStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalcStudioLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(lblNombreApp, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblImagenMywork, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        pnlCalcStudioLayout.setVerticalGroup(
            pnlCalcStudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreApp, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(lblImagenMywork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlOpciones.setBackground(new java.awt.Color(0, 0, 255));
        pnlOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnRectangulo.setBackground(new java.awt.Color(255, 0, 255));
        btnRectangulo.setFont(new java.awt.Font("Noto Serif Display Black", 2, 18)); // NOI18N
        btnRectangulo.setForeground(new java.awt.Color(255, 255, 255));
        btnRectangulo.setText("Rectangulo");
        btnRectangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRectangulo.addActionListener(this::btnRectanguloActionPerformed);

        btnCuadrado.setBackground(new java.awt.Color(255, 0, 255));
        btnCuadrado.setFont(new java.awt.Font("Noto Serif Display Black", 2, 18)); // NOI18N
        btnCuadrado.setForeground(new java.awt.Color(255, 255, 255));
        btnCuadrado.setText("Cuadrado");
        btnCuadrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCuadrado.addActionListener(this::btnCuadradoActionPerformed);

        btnTriangulo.setBackground(new java.awt.Color(255, 0, 255));
        btnTriangulo.setFont(new java.awt.Font("Noto Serif Display Black", 2, 18)); // NOI18N
        btnTriangulo.setForeground(new java.awt.Color(255, 255, 255));
        btnTriangulo.setText("Triangulo");
        btnTriangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTriangulo.addActionListener(this::btnTrianguloActionPerformed);

        btnTrapecio.setBackground(new java.awt.Color(255, 0, 255));
        btnTrapecio.setFont(new java.awt.Font("Noto Serif Display Black", 2, 18)); // NOI18N
        btnTrapecio.setForeground(new java.awt.Color(255, 255, 255));
        btnTrapecio.setText("Trapecio");
        btnTrapecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrapecio.addActionListener(this::btnTrapecioActionPerformed);

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRectangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btnTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btnTrapecio, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblImagenGato.setBackground(new java.awt.Color(255, 102, 255));
        lblImagenGato.setForeground(new java.awt.Color(102, 51, 0));

        pnlSubmenus.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnlAbsolutoProgramaLayout = new javax.swing.GroupLayout(pnlAbsolutoPrograma);
        pnlAbsolutoPrograma.setLayout(pnlAbsolutoProgramaLayout);
        pnlAbsolutoProgramaLayout.setHorizontalGroup(
            pnlAbsolutoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCalcStudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAbsolutoProgramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAbsolutoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagenGato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlSubmenus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pnlAbsolutoProgramaLayout.setVerticalGroup(
            pnlAbsolutoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAbsolutoProgramaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlCalcStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAbsolutoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAbsolutoProgramaLayout.createSequentialGroup()
                        .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagenGato, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addComponent(pnlSubmenus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAbsolutoPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAbsolutoPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloActionPerformed
        // TODO add your handling code here:
        pnlSubmenus.setVisible(true);
        pnlSubmenus.removeAll();
        pnlSubmenus.add(new UI.pnlRectangulo());
        pnlSubmenus.revalidate();
        pnlSubmenus.repaint();
        
        
        
    }//GEN-LAST:event_btnRectanguloActionPerformed

    private void btnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadradoActionPerformed
        // TODO add your handling code here:
        pnlSubmenus.setVisible(true);
        pnlSubmenus.removeAll();
        pnlSubmenus.add(new UI.pnlCuadrado());
        pnlSubmenus.revalidate();
        pnlSubmenus.repaint();
        
    }//GEN-LAST:event_btnCuadradoActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        // TODO add your handling code here:
        pnlSubmenus.setVisible(true);
        pnlSubmenus.removeAll();
        pnlSubmenus.add(new UI.pnlTriangulo());
        pnlSubmenus.revalidate();
        pnlSubmenus.repaint();
        
        
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrapecioActionPerformed
        // TODO add your handling code here:
        pnlSubmenus.setVisible(true);
        pnlSubmenus.removeAll();
        pnlSubmenus.add(new UI.pnlTrapecio());
        pnlSubmenus.revalidate();
        pnlSubmenus.repaint();
    }//GEN-LAST:event_btnTrapecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPantallaInicial().setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JButton btnTrapecio;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JLabel lblImagenGato;
    private javax.swing.JLabel lblImagenMywork;
    private javax.swing.JLabel lblNombreApp;
    private javax.swing.JPanel pnlAbsolutoPrograma;
    private javax.swing.JPanel pnlCalcStudio;
    private javax.swing.JPanel pnlSubmenus;
    // End of variables declaration//GEN-END:variables
}
