/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author CAHR MASTER RACE
 */
public class pnlCuadrado extends javax.swing.JPanel {

    /**
     * Creates new form pnlCuadrado
     */
    public pnlCuadrado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAbsolutoCuadrado = new UI.PanelBackground("/archive/Stone2face.png");
        pnlTitulo = new UI.PanelBackground("/archive/gib_1.png");
        lblTituloCalculoCuadrado = new javax.swing.JLabel();
        lblLado = new javax.swing.JLabel();
        txtCampoLado = new javax.swing.JTextField();
        btnCalcular = new UI.BotonBackground("/archive/fondoBotones.png");
        lblArea = new javax.swing.JLabel();
        lblAreaCalculada = new javax.swing.JLabel();
        lblArea1 = new javax.swing.JLabel();
        lblPerimetroCalculado = new javax.swing.JLabel();

        pnlAbsolutoCuadrado.setBackground(new java.awt.Color(0, 153, 153));
        pnlAbsolutoCuadrado.setPreferredSize(new java.awt.Dimension(695, 401));

        pnlTitulo.setBackground(new java.awt.Color(153, 153, 153));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(218, 48));

        lblTituloCalculoCuadrado.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        lblTituloCalculoCuadrado.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCalculoCuadrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCalculoCuadrado.setText("Calculo Cuadrado");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCalculoCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCalculoCuadrado)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblLado.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblLado.setForeground(new java.awt.Color(255, 255, 255));
        lblLado.setText("Lado:");

        txtCampoLado.addActionListener(this::txtCampoLadoActionPerformed);

        btnCalcular.setBackground(new java.awt.Color(0, 255, 255));
        btnCalcular.setFont(new java.awt.Font("Microsoft YaHei", 3, 12)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        lblArea.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setText("AREA:");

        lblAreaCalculada.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblAreaCalculada.setForeground(new java.awt.Color(255, 255, 255));

        lblArea1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        lblArea1.setForeground(new java.awt.Color(255, 255, 255));
        lblArea1.setText("PERIMETRO:");

        lblPerimetroCalculado.setBackground(new java.awt.Color(255, 255, 255));
        lblPerimetroCalculado.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblPerimetroCalculado.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlAbsolutoCuadradoLayout = new javax.swing.GroupLayout(pnlAbsolutoCuadrado);
        pnlAbsolutoCuadrado.setLayout(pnlAbsolutoCuadradoLayout);
        pnlAbsolutoCuadradoLayout.setHorizontalGroup(
            pnlAbsolutoCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAbsolutoCuadradoLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(pnlAbsolutoCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAbsolutoCuadradoLayout.createSequentialGroup()
                        .addComponent(lblArea1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPerimetroCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAbsolutoCuadradoLayout.createSequentialGroup()
                        .addComponent(lblArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAreaCalculada, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAbsolutoCuadradoLayout.createSequentialGroup()
                        .addComponent(lblLado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtCampoLado)))
                .addGap(172, 172, 172))
        );
        pnlAbsolutoCuadradoLayout.setVerticalGroup(
            pnlAbsolutoCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAbsolutoCuadradoLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(pnlAbsolutoCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtCampoLado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pnlAbsolutoCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAreaCalculada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAbsolutoCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPerimetroCalculado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAbsolutoCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAbsolutoCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCampoLadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoLadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoLadoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try{
            double base = Double.parseDouble(txtCampoLado.getText());

            Modelo.Cuadrado cuadrado = new Modelo.Cuadrado(base, 4);

            double area = cuadrado.area();
            double perimetro = cuadrado.perimetro();

            lblAreaCalculada.setText(Double.toString(area));
            lblPerimetroCalculado.setText(Double.toString(perimetro));
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El programa solo funciona si agregas numeros...");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea1;
    private javax.swing.JLabel lblAreaCalculada;
    private javax.swing.JLabel lblLado;
    private javax.swing.JLabel lblPerimetroCalculado;
    private javax.swing.JLabel lblTituloCalculoCuadrado;
    private javax.swing.JPanel pnlAbsolutoCuadrado;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCampoLado;
    // End of variables declaration//GEN-END:variables
}
