/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;

/**
 *
 * @author CAHR MASTER RACE
 */
public class pnlRectangulo extends javax.swing.JPanel {

    /**
     * Creates new form pnlRectangulo
     */
    public pnlRectangulo() {
        initComponents();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new UI.PanelBackground("/archive/Stone2face.png");
        pnlTitulo = new UI.PanelBackground("/archive/gib_1.png");
        lblTituloCalculoRectangulo = new javax.swing.JLabel();
        lblBase = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        txtCampoBase = new javax.swing.JTextField();
        txtCampoAltura = new javax.swing.JTextField();
        btnCalcular = new UI.BotonBackground("/archive/fondoBotones.png");
        lblAreaCalculada = new javax.swing.JLabel();
        lblPerimetroCalculado = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblArea1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        pnlTitulo.setBackground(new java.awt.Color(102, 255, 102));

        lblTituloCalculoRectangulo.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        lblTituloCalculoRectangulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCalculoRectangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCalculoRectangulo.setText("Calculo Rectangulo");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCalculoRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCalculoRectangulo)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        lblBase.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblBase.setForeground(new java.awt.Color(255, 255, 255));
        lblBase.setText("Base: ");

        lblAltura.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblAltura.setForeground(new java.awt.Color(255, 255, 255));
        lblAltura.setText("Altura:");

        txtCampoBase.addActionListener(this::txtCampoBaseActionPerformed);

        txtCampoAltura.addActionListener(this::txtCampoAlturaActionPerformed);

        btnCalcular.setBackground(new java.awt.Color(0, 255, 255));
        btnCalcular.setFont(new java.awt.Font("Microsoft YaHei", 3, 12)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        lblAreaCalculada.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblAreaCalculada.setForeground(new java.awt.Color(255, 255, 255));

        lblPerimetroCalculado.setBackground(new java.awt.Color(255, 255, 255));
        lblPerimetroCalculado.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblPerimetroCalculado.setForeground(new java.awt.Color(255, 255, 255));

        lblArea.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setText("AREA:");

        lblArea1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        lblArea1.setForeground(new java.awt.Color(255, 255, 255));
        lblArea1.setText("PERIMETRO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArea1)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAreaCalculada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPerimetroCalculado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBase, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCampoAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(txtCampoBase))))
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCampoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lblAreaCalculada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerimetroCalculado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCampoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoBaseActionPerformed

    private void txtCampoAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoAlturaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try{
            double base = Double.parseDouble(txtCampoBase.getText());
            double altura = Double.parseDouble(txtCampoAltura.getText());

            Modelo.Rectangulo rectangulo = new Modelo.Rectangulo(base, altura, 4);

            double area = rectangulo.area();
            double perimetro = rectangulo.perimetro();

            lblAreaCalculada.setText(Double.toString(area));
            lblPerimetroCalculado.setText(Double.toString(perimetro));
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El programa solo funciona si agregas numeros...");
        }

    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea1;
    private javax.swing.JLabel lblAreaCalculada;
    private javax.swing.JLabel lblBase;
    private javax.swing.JLabel lblPerimetroCalculado;
    private javax.swing.JLabel lblTituloCalculoRectangulo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCampoAltura;
    private javax.swing.JTextField txtCampoBase;
    // End of variables declaration//GEN-END:variables
}
