/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author CAHR MASTER RACE
 */
public class pnlTriangulo extends javax.swing.JPanel {

    /**
     * Creates new form pnlTriangulo
     */
    public pnlTriangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAbsolutoTriangulo = new UI.PanelBackground("/archive/Stone2face.png");
        pnlTitulo = new UI.PanelBackground("/archive/gib_1.png");
        lblTituloCalculoTriangulo = new javax.swing.JLabel();
        lblLado1 = new javax.swing.JLabel();
        lblLado2 = new javax.swing.JLabel();
        lblLado3 = new javax.swing.JLabel();
        txtCampoLado1 = new javax.swing.JTextField();
        txtCampoLado2 = new javax.swing.JTextField();
        txtCampoLado3 = new javax.swing.JTextField();
        btnCalcular = new UI.BotonBackground("/archive/fondoBotones.png");
        lblArea = new javax.swing.JLabel();
        lblArea1 = new javax.swing.JLabel();
        lblAreaCalculada = new javax.swing.JLabel();
        lblPerimetroCalculado = new javax.swing.JLabel();

        pnlAbsolutoTriangulo.setBackground(new java.awt.Color(0, 204, 204));
        pnlAbsolutoTriangulo.setPreferredSize(new java.awt.Dimension(695, 401));

        pnlTitulo.setBackground(new java.awt.Color(153, 153, 153));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(218, 48));

        lblTituloCalculoTriangulo.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        lblTituloCalculoTriangulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCalculoTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCalculoTriangulo.setText("Calculo Triangulo");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCalculoTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCalculoTriangulo)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblLado1.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblLado1.setForeground(new java.awt.Color(255, 255, 255));
        lblLado1.setText("Lado 1:");

        lblLado2.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblLado2.setForeground(new java.awt.Color(255, 255, 255));
        lblLado2.setText("Lado 2:");

        lblLado3.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblLado3.setForeground(new java.awt.Color(255, 255, 255));
        lblLado3.setText("Lado 3:");

        txtCampoLado1.addActionListener(this::txtCampoLado1ActionPerformed);

        txtCampoLado2.addActionListener(this::txtCampoLado2ActionPerformed);

        txtCampoLado3.addActionListener(this::txtCampoLado3ActionPerformed);

        btnCalcular.setBackground(new java.awt.Color(0, 255, 255));
        btnCalcular.setFont(new java.awt.Font("Microsoft YaHei", 3, 12)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        lblArea.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setText("AREA:");

        lblArea1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        lblArea1.setForeground(new java.awt.Color(255, 255, 255));
        lblArea1.setText("PERIMETRO:");

        lblAreaCalculada.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblAreaCalculada.setForeground(new java.awt.Color(255, 255, 255));

        lblPerimetroCalculado.setBackground(new java.awt.Color(255, 255, 255));
        lblPerimetroCalculado.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblPerimetroCalculado.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlAbsolutoTrianguloLayout = new javax.swing.GroupLayout(pnlAbsolutoTriangulo);
        pnlAbsolutoTriangulo.setLayout(pnlAbsolutoTrianguloLayout);
        pnlAbsolutoTrianguloLayout.setHorizontalGroup(
            pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
            .addGroup(pnlAbsolutoTrianguloLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAbsolutoTrianguloLayout.createSequentialGroup()
                        .addGroup(pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAbsolutoTrianguloLayout.createSequentialGroup()
                                .addComponent(lblArea)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAbsolutoTrianguloLayout.createSequentialGroup()
                                .addComponent(lblLado3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCampoLado3, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAbsolutoTrianguloLayout.createSequentialGroup()
                                .addComponent(lblLado2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCampoLado2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAbsolutoTrianguloLayout.createSequentialGroup()
                                .addComponent(lblLado1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCampoLado1)))
                        .addGap(196, 196, 196))
                    .addGroup(pnlAbsolutoTrianguloLayout.createSequentialGroup()
                        .addGroup(pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAreaCalculada, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAbsolutoTrianguloLayout.createSequentialGroup()
                                .addComponent(lblArea1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPerimetroCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlAbsolutoTrianguloLayout.setVerticalGroup(
            pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAbsolutoTrianguloLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCampoLado1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCampoLado2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCampoLado3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAreaCalculada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAbsolutoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(lblPerimetroCalculado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAbsolutoTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAbsolutoTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCampoLado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoLado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoLado1ActionPerformed

    private void txtCampoLado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoLado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoLado2ActionPerformed

    private void txtCampoLado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoLado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoLado3ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try{
            double lado1 = Double.parseDouble(txtCampoLado1.getText());
            double lado2 = Double.parseDouble(txtCampoLado2.getText());
            double lado3 = Double.parseDouble(txtCampoLado3.getText());

            Modelo.Triangulo triangulo = new Modelo.Triangulo(lado1, lado2, lado3, 3);

            double area = triangulo.area();
            double perimetro = triangulo.perimetro();

            lblAreaCalculada.setText(Double.toString(area));
            lblPerimetroCalculado.setText(Double.toString(perimetro));
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El programa solo funciona si agregas numeros...");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea1;
    private javax.swing.JLabel lblAreaCalculada;
    private javax.swing.JLabel lblLado1;
    private javax.swing.JLabel lblLado2;
    private javax.swing.JLabel lblLado3;
    private javax.swing.JLabel lblPerimetroCalculado;
    private javax.swing.JLabel lblTituloCalculoTriangulo;
    private javax.swing.JPanel pnlAbsolutoTriangulo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCampoLado1;
    private javax.swing.JTextField txtCampoLado2;
    private javax.swing.JTextField txtCampoLado3;
    // End of variables declaration//GEN-END:variables
}
