/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Modelo.Trapecio;

/**
 *
 * @author CAHR MASTER RACE
 */
public class pnlTrapecio extends javax.swing.JPanel {

    /**
     * Creates new form pnlTrapecio
     */
    public pnlTrapecio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAbsolutoTrapecio = new UI.PanelBackground("/archive/Stone2face.png");
        pnlTitulo = new UI.PanelBackground("/archive/gib_1.png");
        lblTituloCalculoTrapecio = new javax.swing.JLabel();
        lblBaseMayor = new javax.swing.JLabel();
        lblBaseMenor1 = new javax.swing.JLabel();
        txtCampoBaseMenor = new javax.swing.JTextField();
        txtCampoBaseMayor = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        txtCampoAltura = new javax.swing.JTextField();
        lblLado1 = new javax.swing.JLabel();
        txtCampoLado1 = new javax.swing.JTextField();
        lblLado2 = new javax.swing.JLabel();
        txtCampoLado2 = new javax.swing.JTextField();
        btnCalcular = new UI.BotonBackground("/archive/fondoBotones.png");
        lblArea = new javax.swing.JLabel();
        lblAreaCalculada = new javax.swing.JLabel();
        lblArea1 = new javax.swing.JLabel();
        lblPerimetroCalculado = new javax.swing.JLabel();

        pnlAbsolutoTrapecio.setBackground(new java.awt.Color(0, 102, 102));

        pnlTitulo.setBackground(new java.awt.Color(102, 255, 102));

        lblTituloCalculoTrapecio.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        lblTituloCalculoTrapecio.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCalculoTrapecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCalculoTrapecio.setText("Calculo Trapecio");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCalculoTrapecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCalculoTrapecio)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        lblBaseMayor.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblBaseMayor.setForeground(new java.awt.Color(255, 255, 255));
        lblBaseMayor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBaseMayor.setText("Base mayor:");

        lblBaseMenor1.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblBaseMenor1.setForeground(new java.awt.Color(255, 255, 255));
        lblBaseMenor1.setText("Base menor:");

        txtCampoBaseMenor.addActionListener(this::txtCampoBaseMenorActionPerformed);

        txtCampoBaseMayor.addActionListener(this::txtCampoBaseMayorActionPerformed);

        lblAltura.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblAltura.setForeground(new java.awt.Color(255, 255, 255));
        lblAltura.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAltura.setText("Altura:");

        txtCampoAltura.addActionListener(this::txtCampoAlturaActionPerformed);

        lblLado1.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblLado1.setForeground(new java.awt.Color(255, 255, 255));
        lblLado1.setText("Lado 1:");

        txtCampoLado1.addActionListener(this::txtCampoLado1ActionPerformed);

        lblLado2.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblLado2.setForeground(new java.awt.Color(255, 255, 255));
        lblLado2.setText("Lado 2:");

        txtCampoLado2.addActionListener(this::txtCampoLado2ActionPerformed);

        btnCalcular.setBackground(new java.awt.Color(0, 255, 255));
        btnCalcular.setFont(new java.awt.Font("Microsoft YaHei", 3, 12)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        lblArea.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setText("AREA:");

        lblAreaCalculada.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblAreaCalculada.setForeground(new java.awt.Color(255, 255, 255));

        lblArea1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        lblArea1.setForeground(new java.awt.Color(255, 255, 255));
        lblArea1.setText("PERIMETRO:");

        lblPerimetroCalculado.setBackground(new java.awt.Color(255, 255, 255));
        lblPerimetroCalculado.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        lblPerimetroCalculado.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlAbsolutoTrapecioLayout = new javax.swing.GroupLayout(pnlAbsolutoTrapecio);
        pnlAbsolutoTrapecio.setLayout(pnlAbsolutoTrapecioLayout);
        pnlAbsolutoTrapecioLayout.setHorizontalGroup(
            pnlAbsolutoTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAbsolutoTrapecioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlAbsolutoTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAbsolutoTrapecioLayout.createSequentialGroup()
                        .addComponent(lblArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAreaCalculada, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblArea1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPerimetroCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(pnlAbsolutoTrapecioLayout.createSequentialGroup()
                        .addGroup(pnlAbsolutoTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAbsolutoTrapecioLayout.createSequentialGroup()
                                .addComponent(lblBaseMenor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCampoBaseMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAbsolutoTrapecioLayout.createSequentialGroup()
                                .addComponent(lblAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAbsolutoTrapecioLayout.createSequentialGroup()
                                .addComponent(lblBaseMayor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCampoBaseMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAbsolutoTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAbsolutoTrapecioLayout.createSequentialGroup()
                                .addComponent(lblLado2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCampoLado2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAbsolutoTrapecioLayout.createSequentialGroup()
                                .addComponent(lblLado1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCampoLado1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlAbsolutoTrapecioLayout.setVerticalGroup(
            pnlAbsolutoTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAbsolutoTrapecioLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(pnlAbsolutoTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBaseMenor1)
                    .addComponent(txtCampoBaseMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLado1)
                    .addComponent(txtCampoLado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAbsolutoTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCampoBaseMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBaseMayor)
                    .addComponent(lblLado2)
                    .addComponent(txtCampoLado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAbsolutoTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtCampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addGap(95, 95, 95)
                .addGroup(pnlAbsolutoTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lblAreaCalculada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPerimetroCalculado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAbsolutoTrapecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAbsolutoTrapecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCampoBaseMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoBaseMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoBaseMenorActionPerformed

    private void txtCampoBaseMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoBaseMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoBaseMayorActionPerformed

    private void txtCampoAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoAlturaActionPerformed

    private void txtCampoLado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoLado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoLado1ActionPerformed

    private void txtCampoLado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoLado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoLado2ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try{
            double baseMayor = Double.parseDouble(txtCampoBaseMayor.getText());
            double baseMenor = Double.parseDouble(txtCampoBaseMenor.getText());
            double lado1 = Double.parseDouble(txtCampoLado1.getText());
            double lado2= Double.parseDouble(txtCampoLado2.getText());
            double altura = Double.parseDouble(txtCampoAltura.getText());

            Modelo.Trapecio trapecio = new Trapecio(baseMenor, baseMayor, altura, lado1, lado2, 4);
            
            double area = trapecio.area();
            double perimetro = trapecio.perimetro();

            lblAreaCalculada.setText(Double.toString(area));
            lblPerimetroCalculado.setText(Double.toString(perimetro));
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El programa solo funciona si agregas numeros...");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea1;
    private javax.swing.JLabel lblAreaCalculada;
    private javax.swing.JLabel lblBaseMayor;
    private javax.swing.JLabel lblBaseMenor1;
    private javax.swing.JLabel lblLado1;
    private javax.swing.JLabel lblLado2;
    private javax.swing.JLabel lblPerimetroCalculado;
    private javax.swing.JLabel lblTituloCalculoTrapecio;
    private javax.swing.JPanel pnlAbsolutoTrapecio;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCampoAltura;
    private javax.swing.JTextField txtCampoBaseMayor;
    private javax.swing.JTextField txtCampoBaseMenor;
    private javax.swing.JTextField txtCampoLado1;
    private javax.swing.JTextField txtCampoLado2;
    // End of variables declaration//GEN-END:variables
}
